// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: proto/tours/tours.proto

package tours

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ===== Messages =====
type AbandonTourExecutionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TourExecutionId int64                  `protobuf:"varint,1,opt,name=tourExecutionId,proto3" json:"tourExecutionId,omitempty"` // iz URL-a
	Latitude        float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`              // iz body-ja
	Longitude       float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`            // iz body-ja
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AbandonTourExecutionRequest) Reset() {
	*x = AbandonTourExecutionRequest{}
	mi := &file_proto_tours_tours_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbandonTourExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbandonTourExecutionRequest) ProtoMessage() {}

func (x *AbandonTourExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tours_tours_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbandonTourExecutionRequest.ProtoReflect.Descriptor instead.
func (*AbandonTourExecutionRequest) Descriptor() ([]byte, []int) {
	return file_proto_tours_tours_proto_rawDescGZIP(), []int{0}
}

func (x *AbandonTourExecutionRequest) GetTourExecutionId() int64 {
	if x != nil {
		return x.TourExecutionId
	}
	return 0
}

func (x *AbandonTourExecutionRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *AbandonTourExecutionRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type CompleteTourExecutionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TourExecutionId int64                  `protobuf:"varint,1,opt,name=tourExecutionId,proto3" json:"tourExecutionId,omitempty"` // iz URL-a
	Latitude        float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`              // iz body-ja
	Longitude       float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`            // iz body-ja
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CompleteTourExecutionRequest) Reset() {
	*x = CompleteTourExecutionRequest{}
	mi := &file_proto_tours_tours_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteTourExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteTourExecutionRequest) ProtoMessage() {}

func (x *CompleteTourExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tours_tours_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteTourExecutionRequest.ProtoReflect.Descriptor instead.
func (*CompleteTourExecutionRequest) Descriptor() ([]byte, []int) {
	return file_proto_tours_tours_proto_rawDescGZIP(), []int{1}
}

func (x *CompleteTourExecutionRequest) GetTourExecutionId() int64 {
	if x != nil {
		return x.TourExecutionId
	}
	return 0
}

func (x *CompleteTourExecutionRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *CompleteTourExecutionRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type CompletedCheckpointResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CheckpointId   int64                  `protobuf:"varint,1,opt,name=checkpointId,proto3" json:"checkpointId,omitempty"`
	CompletionTime int64                  `protobuf:"varint,2,opt,name=completionTime,proto3" json:"completionTime,omitempty"` // Unix timestamp (seconds)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CompletedCheckpointResponse) Reset() {
	*x = CompletedCheckpointResponse{}
	mi := &file_proto_tours_tours_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompletedCheckpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletedCheckpointResponse) ProtoMessage() {}

func (x *CompletedCheckpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tours_tours_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletedCheckpointResponse.ProtoReflect.Descriptor instead.
func (*CompletedCheckpointResponse) Descriptor() ([]byte, []int) {
	return file_proto_tours_tours_proto_rawDescGZIP(), []int{2}
}

func (x *CompletedCheckpointResponse) GetCheckpointId() int64 {
	if x != nil {
		return x.CheckpointId
	}
	return 0
}

func (x *CompletedCheckpointResponse) GetCompletionTime() int64 {
	if x != nil {
		return x.CompletionTime
	}
	return 0
}

type TourExecutionResponse struct {
	state                protoimpl.MessageState         `protogen:"open.v1"`
	Id                   int64                          `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TourId               int64                          `protobuf:"varint,2,opt,name=tourId,proto3" json:"tourId,omitempty"`
	TouristId            int64                          `protobuf:"varint,3,opt,name=touristId,proto3" json:"touristId,omitempty"`
	Status               string                         `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	LastActivity         int64                          `protobuf:"varint,5,opt,name=lastActivity,proto3" json:"lastActivity,omitempty"` // Unix timestamp (seconds)
	Completion           float64                        `protobuf:"fixed64,6,opt,name=completion,proto3" json:"completion,omitempty"`
	Longitude            float64                        `protobuf:"fixed64,7,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude             float64                        `protobuf:"fixed64,8,opt,name=latitude,proto3" json:"latitude,omitempty"`
	CompletedCheckpoints []*CompletedCheckpointResponse `protobuf:"bytes,9,rep,name=completedCheckpoints,proto3" json:"completedCheckpoints,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TourExecutionResponse) Reset() {
	*x = TourExecutionResponse{}
	mi := &file_proto_tours_tours_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TourExecutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TourExecutionResponse) ProtoMessage() {}

func (x *TourExecutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tours_tours_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TourExecutionResponse.ProtoReflect.Descriptor instead.
func (*TourExecutionResponse) Descriptor() ([]byte, []int) {
	return file_proto_tours_tours_proto_rawDescGZIP(), []int{3}
}

func (x *TourExecutionResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TourExecutionResponse) GetTourId() int64 {
	if x != nil {
		return x.TourId
	}
	return 0
}

func (x *TourExecutionResponse) GetTouristId() int64 {
	if x != nil {
		return x.TouristId
	}
	return 0
}

func (x *TourExecutionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TourExecutionResponse) GetLastActivity() int64 {
	if x != nil {
		return x.LastActivity
	}
	return 0
}

func (x *TourExecutionResponse) GetCompletion() float64 {
	if x != nil {
		return x.Completion
	}
	return 0
}

func (x *TourExecutionResponse) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *TourExecutionResponse) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *TourExecutionResponse) GetCompletedCheckpoints() []*CompletedCheckpointResponse {
	if x != nil {
		return x.CompletedCheckpoints
	}
	return nil
}

var File_proto_tours_tours_proto protoreflect.FileDescriptor

const file_proto_tours_tours_proto_rawDesc = "" +
	"\n" +
	"\x17proto/tours/tours.proto\x12\x05tours\x1a\x1cgoogle/api/annotations.proto\"\x81\x01\n" +
	"\x1bAbandonTourExecutionRequest\x12(\n" +
	"\x0ftourExecutionId\x18\x01 \x01(\x03R\x0ftourExecutionId\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\"\x82\x01\n" +
	"\x1cCompleteTourExecutionRequest\x12(\n" +
	"\x0ftourExecutionId\x18\x01 \x01(\x03R\x0ftourExecutionId\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\"i\n" +
	"\x1bCompletedCheckpointResponse\x12\"\n" +
	"\fcheckpointId\x18\x01 \x01(\x03R\fcheckpointId\x12&\n" +
	"\x0ecompletionTime\x18\x02 \x01(\x03R\x0ecompletionTime\"\xcb\x02\n" +
	"\x15TourExecutionResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06tourId\x18\x02 \x01(\x03R\x06tourId\x12\x1c\n" +
	"\ttouristId\x18\x03 \x01(\x03R\ttouristId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\"\n" +
	"\flastActivity\x18\x05 \x01(\x03R\flastActivity\x12\x1e\n" +
	"\n" +
	"completion\x18\x06 \x01(\x01R\n" +
	"completion\x12\x1c\n" +
	"\tlongitude\x18\a \x01(\x01R\tlongitude\x12\x1a\n" +
	"\blatitude\x18\b \x01(\x01R\blatitude\x12V\n" +
	"\x14completedCheckpoints\x18\t \x03(\v2\".tours.CompletedCheckpointResponseR\x14completedCheckpoints2\xd1\x02\n" +
	"\x14TourExecutionService\x12\x99\x01\n" +
	"\x14AbandonTourExecution\x12\".tours.AbandonTourExecutionRequest\x1a\x1c.tours.TourExecutionResponse\"?\x82\xd3\xe4\x93\x029:\x01*\x1a4/api/tours/tour-executions/abandon/{tourExecutionId}\x12\x9c\x01\n" +
	"\x15CompleteTourExecution\x12#.tours.CompleteTourExecutionRequest\x1a\x1c.tours.TourExecutionResponse\"@\x82\xd3\xe4\x93\x02::\x01*\x1a5/api/tours/tour-executions/complete/{tourExecutionId}B\x19Z\vproto/tours\xaa\x02\tTours.Apib\x06proto3"

var (
	file_proto_tours_tours_proto_rawDescOnce sync.Once
	file_proto_tours_tours_proto_rawDescData []byte
)

func file_proto_tours_tours_proto_rawDescGZIP() []byte {
	file_proto_tours_tours_proto_rawDescOnce.Do(func() {
		file_proto_tours_tours_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_tours_tours_proto_rawDesc), len(file_proto_tours_tours_proto_rawDesc)))
	})
	return file_proto_tours_tours_proto_rawDescData
}

var file_proto_tours_tours_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_tours_tours_proto_goTypes = []any{
	(*AbandonTourExecutionRequest)(nil),  // 0: tours.AbandonTourExecutionRequest
	(*CompleteTourExecutionRequest)(nil), // 1: tours.CompleteTourExecutionRequest
	(*CompletedCheckpointResponse)(nil),  // 2: tours.CompletedCheckpointResponse
	(*TourExecutionResponse)(nil),        // 3: tours.TourExecutionResponse
}
var file_proto_tours_tours_proto_depIdxs = []int32{
	2, // 0: tours.TourExecutionResponse.completedCheckpoints:type_name -> tours.CompletedCheckpointResponse
	0, // 1: tours.TourExecutionService.AbandonTourExecution:input_type -> tours.AbandonTourExecutionRequest
	1, // 2: tours.TourExecutionService.CompleteTourExecution:input_type -> tours.CompleteTourExecutionRequest
	3, // 3: tours.TourExecutionService.AbandonTourExecution:output_type -> tours.TourExecutionResponse
	3, // 4: tours.TourExecutionService.CompleteTourExecution:output_type -> tours.TourExecutionResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_tours_tours_proto_init() }
func file_proto_tours_tours_proto_init() {
	if File_proto_tours_tours_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_tours_tours_proto_rawDesc), len(file_proto_tours_tours_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_tours_tours_proto_goTypes,
		DependencyIndexes: file_proto_tours_tours_proto_depIdxs,
		MessageInfos:      file_proto_tours_tours_proto_msgTypes,
	}.Build()
	File_proto_tours_tours_proto = out.File
	file_proto_tours_tours_proto_goTypes = nil
	file_proto_tours_tours_proto_depIdxs = nil
}
